begin;
insert into user (id, enabled, email, name, password_digest)values (1, 1, 'cbd@gmail.com', 'CBD','$2a$10$bXKb5AEJDBHKeAOotCNk8.Mkr3j1Jl8/3UKwOl8aLdasg12Gt7Kz.');
insert into access_token (user_id, token, expired_at)values (1, 'user1-token', '2038-01-01');
insert into access_token (user_id, token, expired_at)values (1, 'token-expired', '2012-12-21');
insert into product (id, creator_id, title, description)values (1, 1, 'product A', 'Product details A');
insert into product (id, creator_id, title, description)values (2, 1, 'product B', 'Product details B');
insert into listing (id, project_id, creator_id, title, description)values (1, 1, 1, 'Listing A', 'Listing details A');
insert into listing (id, project_id, creator_id, title, description)values (2, 1, 1, 'Listing B', 'Listing details B');
insert into task (id, listing_id, creator_id, parent_id, title, description)values (1, 1, 1, null, 'task-1', 't1');
insert into task (id, listing_id, creator_id, parent_id, title, description)values (2, 1, 1, null, 'task-2', 't2');
insert into task (id, listing_id, creator_id, parent_id, title, description)values (3, 1, 1, null, 'task-3', 't3');
insert into task (id, listing_id, creator_id, parent_id, title, description)values (4, 1, 1, 2, 'task-2-4', 't4');
insert into task (id, listing_id, creator_id, parent_id, title, description)values (5, 1, 1, 2, 'task-2-5', 't5');
insert into task (id, listing_id, creator_id, parent_id, title, description)values (6, 1, 1, 2, 'task-2-6', 't6');
insert into task (id, listing_id, creator_id, parent_id, title, description)values (7, 1, 1, 3, 'task-3-7', 't7');
insert into task (id, listing_id, creator_id, parent_id, title, description)values (8, 1, 1, 7, 'task-3-7-8', 't8');
insert into task (id, listing_id, creator_id, parent_id, title, description)values (9, 1, 1, 7, 'task-3-7-9', 't9');
commit;
